# _____   _____          _     _____  ______  _____ _______            _____ _____
# |  __ \ / ____|        | |   |  __ \|  ____|/ ____|__   __|     /\   |  __ \_   _|
# | |__) | |     __ _ ___| |_  | |__) | |__  | (___    | |______ /  \  | |__) || |
# |  ___/| |    / _` / __| __| |  _  /|  __|  \___ \   | |______/ /\ \ |  ___/ | |
# | |    | |___| (_| \__ \ |_  | | \ \| |____ ____) |  | |     / ____ \| |    _| |_
# |_|     \_____\__,_|___/\__| |_|  \_\______|_____/   |_|    /_/    \_\_|   |_____|

[server]
host = ""
port = 8080
logging = true
log_level = "debug"
log_format = "${remote_ip} [${time_rfc3339}] \"${method} ${uri} ${protocol}\" ${status} ${bytes_out} ${user_agent}\n"

[database]
host = "localhost"
port = 5432
database = "pcast"
user = "pcast"
password = "pcast"
max_connections = 20
max_idle_connections = 10
max_lifetime = "1h"
logging = false
