// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episode.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (id, created_at, updated_at, feed_id, feed_guid, current_position, played)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, feed_id, feed_guid, current_position, played
`

type CreateEpisodeParams struct {
	ID              uuid.UUID     `json:"id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	FeedID          uuid.UUID     `json:"feed_id"`
	FeedGuid        string        `json:"feed_guid"`
	CurrentPosition sql.NullInt32 `json:"current_position"`
	Played          bool          `json:"played"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (*Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisode,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedID,
		arg.FeedGuid,
		arg.CurrentPosition,
		arg.Played,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.FeedGuid,
		&i.CurrentPosition,
		&i.Played,
	)
	return &i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEpisode, id)
	return err
}

const findAllEpisodes = `-- name: FindAllEpisodes :many
SELECT id, created_at, updated_at, feed_id, feed_guid, current_position, played FROM episodes ORDER BY created_at DESC
`

func (q *Queries) FindAllEpisodes(ctx context.Context) ([]*Episode, error) {
	rows, err := q.db.QueryContext(ctx, findAllEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedID,
			&i.FeedGuid,
			&i.CurrentPosition,
			&i.Played,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEpisodeByID = `-- name: FindEpisodeByID :one
SELECT id, created_at, updated_at, feed_id, feed_guid, current_position, played FROM episodes WHERE id = $1
`

func (q *Queries) FindEpisodeByID(ctx context.Context, id uuid.UUID) (*Episode, error) {
	row := q.db.QueryRowContext(ctx, findEpisodeByID, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.FeedGuid,
		&i.CurrentPosition,
		&i.Played,
	)
	return &i, err
}

const updateEpisode = `-- name: UpdateEpisode :exec
UPDATE episodes 
SET updated_at = $2, feed_id = $3, feed_guid = $4, current_position = $5, played = $6
WHERE id = $1
`

type UpdateEpisodeParams struct {
	ID              uuid.UUID     `json:"id"`
	UpdatedAt       time.Time     `json:"updated_at"`
	FeedID          uuid.UUID     `json:"feed_id"`
	FeedGuid        string        `json:"feed_guid"`
	CurrentPosition sql.NullInt32 `json:"current_position"`
	Played          bool          `json:"played"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisode,
		arg.ID,
		arg.UpdatedAt,
		arg.FeedID,
		arg.FeedGuid,
		arg.CurrentPosition,
		arg.Played,
	)
	return err
}
