// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, user_id, title, url, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, user_id, title, url, synced_at
`

type CreateFeedParams struct {
	ID        uuid.UUID    `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Url       string       `json:"url"`
	SyncedAt  sql.NullTime `json:"synced_at"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (*Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Title,
		arg.Url,
		arg.SyncedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.SyncedAt,
	)
	return &i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = $1
`

func (q *Queries) DeleteFeed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const findAllFeeds = `-- name: FindAllFeeds :many
SELECT id, created_at, updated_at, user_id, title, url, synced_at FROM feeds ORDER BY created_at DESC
`

func (q *Queries) FindAllFeeds(ctx context.Context) ([]*Feed, error) {
	rows, err := q.db.QueryContext(ctx, findAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.Url,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFeedByID = `-- name: FindFeedByID :one
SELECT id, created_at, updated_at, user_id, title, url, synced_at FROM feeds WHERE id = $1
`

func (q *Queries) FindFeedByID(ctx context.Context, id uuid.UUID) (*Feed, error) {
	row := q.db.QueryRowContext(ctx, findFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.SyncedAt,
	)
	return &i, err
}

const findFeedByIDAndUserID = `-- name: FindFeedByIDAndUserID :one
SELECT id, created_at, updated_at, user_id, title, url, synced_at FROM feeds WHERE id = $1 AND user_id = $2
`

type FindFeedByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) FindFeedByIDAndUserID(ctx context.Context, arg FindFeedByIDAndUserIDParams) (*Feed, error) {
	row := q.db.QueryRowContext(ctx, findFeedByIDAndUserID, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.SyncedAt,
	)
	return &i, err
}

const findFeedsByUserID = `-- name: FindFeedsByUserID :many
SELECT id, created_at, updated_at, user_id, title, url, synced_at FROM feeds WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) FindFeedsByUserID(ctx context.Context, userID uuid.UUID) ([]*Feed, error) {
	rows, err := q.db.QueryContext(ctx, findFeedsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.Url,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds
SET updated_at = $2, user_id = $3, title = $4, url = $5, synced_at = $6
WHERE id = $1
`

type UpdateFeedParams struct {
	ID        uuid.UUID    `json:"id"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Url       string       `json:"url"`
	SyncedAt  sql.NullTime `json:"synced_at"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed,
		arg.ID,
		arg.UpdatedAt,
		arg.UserID,
		arg.Title,
		arg.Url,
		arg.SyncedAt,
	)
	return err
}
