// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Episode struct {
	ID              uuid.UUID     `json:"id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	FeedID          uuid.UUID     `json:"feed_id"`
	FeedGuid        string        `json:"feed_guid"`
	CurrentPosition sql.NullInt32 `json:"current_position"`
	Played          bool          `json:"played"`
}

type Feed struct {
	ID        uuid.UUID    `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Url       string       `json:"url"`
	SyncedAt  sql.NullTime `json:"synced_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
}
