version: '3.8'
name: pcast-api
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pcast
      POSTGRES_PASSWORD: pcast
      POSTGRES_DB: pcast
    ports:
      - "5432:5432"
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
